name: Test React App
on: 
    push: 
        branches: 
           - 'master'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Test application
        run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
        - name: Get repository name
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm i
        - name: Build Application
          run: npm run build
        - name: Deploy
          run: echo Deploying...