name: Print Pull Request Context
on: 
    workflow_dispatch: 
    pull_request: 
        types: [opened, edited, reopened]
jobs:
  print_context:  # Добавлено имя для задания
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo "${{ toJson(github.event) }}"  # Используйте toJson для корректного отображения объекта