name: Print Pull Request Context
on: workflow_dispatch
jobs:
  print_context:  # Добавлено имя для задания
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo "${{ github }}"  # Используйте toJson для корректного отображения объекта